import { Metadata } from "next";
import { Scale } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service — LEXORA",
  description: "The terms and conditions for using LEXORA.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container mx-auto max-w-3xl px-6 py-16">
        <div className="flex items-center gap-2.5 mb-8">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary">
            <Scale className="h-5 w-5 text-primary-foreground" strokeWidth={2.2} />
          </div>
          <span className="text-[17px] font-bold tracking-tight">LEXORA</span>
        </div>
        <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="prose prose-invert max-w-none space-y-6 text-[15px] leading-relaxed text-muted-foreground">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using LEXORA (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>LEXORA is an AI-powered contract intelligence platform that analyzes legal documents, identifies risky clauses, explains legal language in plain English, and generates counter-proposals. The Service is provided for informational purposes only and does not constitute legal advice.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. Not Legal Advice</h2>
            <p><strong className="text-foreground">IMPORTANT:</strong> LEXORA is not a law firm and does not provide legal advice. The analyses, risk scores, counter-proposals, and other outputs generated by the Service are for informational purposes only and should not be relied upon as legal advice.</p>
            <p className="mt-2">Always consult with a qualified attorney before making legal decisions or signing contracts. We are not liable for any decisions made based on the Service's output.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Account Registration</h2>
            <p>To use the Service, you must:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Be at least 18 years old</li>
              <li>Provide accurate and complete information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Be responsible for all activities under your account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. Subscription and Billing</h2>
            <p>The Service offers free and paid subscription plans. Paid plans are billed through Stripe on a monthly or yearly basis.</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Subscription fees are charged in advance</li>
              <li>You can cancel your subscription at any time</li>
              <li>Cancellations take effect at the end of the current billing period</li>
              <li>No refunds are provided for partial billing periods</li>
              <li>We may change pricing with 30 days notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>Use the Service for any illegal purpose</li>
              <li>Upload contracts you do not have the right to analyze</li>
              <li>Attempt to reverse engineer or access the Service's internals</li>
              <li>Abuse, overload, or disrupt the Service</li>
              <li>Share your account credentials with others</li>
              <li>Use the Service to provide legal advice to others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Your Content</h2>
            <p>You retain ownership of the contracts and documents you upload ("Your Content"). By uploading, you grant us a limited license to process Your Content through the Service and AI providers for the purpose of providing analysis.</p>
            <p className="mt-2">You are responsible for ensuring you have the right to upload and analyze Your Content.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. AI Accuracy Disclaimer</h2>
            <p>The Service uses artificial intelligence to analyze contracts. AI analysis may contain errors, omissions, or inaccuracies. The Service may miss important clauses or misinterpret contract terms.</p>
            <p className="mt-2">You must independently verify all analysis results. Do not rely solely on the Service's output when making legal or business decisions.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. Intellectual Property</h2>
            <p>The Service, including its design, features, and underlying technology, is owned by LEXORA and protected by intellectual property laws. You may not copy, modify, or distribute the Service without permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">10. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law:</p>
            <ul className="list-disc pl-6 space-y-1 mt-2">
              <li>The Service is provided "as is" without warranties</li>
              <li>We are not liable for indirect, incidental, or consequential damages</li>
              <li>Our total liability is limited to the amount you paid in the prior 12 months</li>
              <li>We are not liable for any legal consequences arising from contract analysis</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">11. Termination</h2>
            <p>We may suspend or terminate your account if you violate these Terms. You may delete your account at any time. Upon termination, your data will be deleted within 30 days.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">12. Changes to Terms</h2>
            <p>We may update these Terms from time to time. We will notify you of material changes via email. Continued use after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">13. Governing Law</h2>
            <p>These Terms are governed by the laws of your jurisdiction, without regard to conflict of law principles.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">14. Contact</h2>
            <p>For questions about these Terms, contact us at: legal@lexora.com</p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-border">
          <a href="/" className="text-sm text-primary hover:underline">← Back to LEXORA</a>
        </div>
      </div>
    </div>
  );
}
